import type { Tour } from '@/types';

const tours: Tour[] = [
  {
    id: '1',
    name: 'Kyoto Cultural Expedition',
    destination: 'Japan',
    type: 'Cultural',
    duration: 7,
    price: 2500,
    description: 'Immerse yourself in the ancient culture of Kyoto. Visit serene temples, walk through bamboo groves, and experience a traditional tea ceremony.',
    itinerary: [
      { day: 1, activity: 'Arrival in Kyoto, check-in to Ryokan' },
      { day: 2, activity: 'Visit Kinkaku-ji (Golden Pavilion) and Ryoan-ji Temple' },
      { day: 3, activity: 'Explore Arashiyama Bamboo Grove and Tenryu-ji Temple' },
      { day: 4, activity: 'Gion district tour and traditional tea ceremony' },
      { day: 5, activity: 'Day trip to Fushimi Inari Shrine' },
      { day: 6, activity: 'Free day for shopping or personal exploration' },
      { day: 7, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Swiss Alps Adventure',
    destination: 'Switzerland',
    type: 'Adventure',
    duration: 10,
    price: 4000,
    description: 'Embark on an exhilarating adventure through the Swiss Alps. Hike stunning trails, paraglide over valleys, and enjoy breathtaking mountain views.',
    itinerary: [
      { day: 1, activity: 'Arrival in Interlaken' },
      { day: 2, activity: 'Hiking in the Jungfrau region' },
      { day: 3, activity: 'Paragliding over Interlaken' },
      { day: 4, activity: 'Train journey to Zermatt' },
      { day: 5, activity: 'View the Matterhorn and hike local trails' },
      { day: 6, activity: 'Explore Gorner Gorge' },
      { day: 7, activity: 'Travel to Lucerne' },
      { day: 8, activity: 'Lake Lucerne boat trip and Mount Pilatus' },
      { day: 9, activity: 'Free day in Lucerne' },
      { day: 10, activity: 'Departure from Zurich' },
    ],
    availability: true,
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Tuscan Culinary Journey',
    destination: 'Italy',
    type: 'Culinary',
    duration: 5,
    price: 2200,
    description: 'Indulge in the flavors of Tuscany. Participate in cooking classes, visit local wineries, and savor authentic Italian cuisine in the heart of the countryside.',
    itinerary: [
      { day: 1, activity: 'Arrival in Florence, welcome dinner' },
      { day: 2, activity: 'Tuscan cooking class at a farmhouse' },
      { day: 3, activity: 'Chianti wine tasting tour' },
      { day: 4, activity: 'Explore Siena and San Gimignano' },
      { day: 5, activity: 'Departure' },
    ],
    availability: false,
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Maldives Tropical Relaxation',
    destination: 'Maldives',
    type: 'Relaxation',
    duration: 8,
    price: 5500,
    description: 'Escape to a paradise of white-sand beaches and crystal-clear waters. Relax in an overwater bungalow, snorkel among vibrant coral reefs, and enjoy ultimate tranquility.',
    itinerary: [
        { day: 1, activity: 'Arrival at Malé airport, speedboat transfer to resort' },
        { day: 2, activity: 'Relax on the beach, enjoy resort amenities' },
        { day: 3, activity: 'Guided snorkeling tour' },
        { day: 4, activity: 'Sunset dolphin cruise' },
        { day: 5, activity: 'Spa and wellness day' },
        { day: 6, activity: 'Private beach dinner' },
        { day: 7, activity: 'Free day for watersports or relaxation' },
        { day: 8, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: '5',
    name: 'Patagonia Hiking Trek',
    destination: 'Chile',
    type: 'Adventure',
    duration: 12,
    price: 4800,
    description: "Discover the rugged beauty of Torres del Paine National Park. This challenging trek offers stunning glaciers, pristine lakes, and iconic mountain peaks.",
    itinerary: [
      { day: 1, activity: 'Arrival in Punta Arenas, transfer to Puerto Natales' },
      { day: 2, activity: 'Enter Torres del Paine, begin W-Trek' },
      { day: 3, activity: 'Hike to the base of the towers' },
      { day: 4, activity: 'Hike along Lake Nordenskjöld' },
      { day: 5, activity: 'Trek into the French Valley' },
      { day: 6, activity: 'Hike to Paine Grande and Grey Lake' },
      { day: 7, activity: 'Grey Glacier viewpoint hike' },
      { day: 8, activity: 'Catamaran across Pehoé Lake, return to Puerto Natales' },
      { day: 9, activity: 'Rest day in Puerto Natales' },
      { day: 10, activity: 'Day trip to Balmaceda and Serrano Glaciers' },
      { day: 11, activity: 'Explore local culture and cuisine' },
      { day: 12, activity: 'Departure from Punta Arenas' },
    ],
    availability: true,
    image: 'https://placehold.co/600x400.png',
    rating: 5.0,
  },
  {
    id: '6',
    name: 'Santorini Sunset Escape',
    destination: 'Greece',
    type: 'Relaxation',
    duration: 4,
    price: 1800,
    description: 'Experience the magic of Santorini. Watch iconic sunsets from Oia, explore charming villages, and relax on unique volcanic sand beaches.',
    itinerary: [
        { day: 1, activity: 'Arrival in Santorini, transfer to Oia' },
        { day: 2, activity: 'Explore Fira and local villages' },
        { day: 3, activity: 'Catamaran cruise to hot springs and Red Beach' },
        { day: 4, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  }
];

export const getTours = (): Tour[] => tours;

export const getTourById = (id: string): Tour | undefined => tours.find(tour => tour.id === id);
