import type { Tour } from '@/types';

const tours: Tour[] = [
  {
    id: '1',
    name: 'Pyramids & Sphinx Expedition',
    destination: 'Cairo',
    type: 'Cultural',
    duration: 3,
    priceTiers: [
        { minPeople: 1, maxPeople: 1, pricePerAdult: 150, pricePerChild: 80 },
        { minPeople: 2, maxPeople: 5, pricePerAdult: 90, pricePerChild: 50 },
        { minPeople: 6, maxPeople: null, pricePerAdult: 75, pricePerChild: 40 },
    ],
    description: 'Explore the iconic Pyramids of Giza and the majestic Sphinx. A journey back in time to the land of Pharaohs.',
    itinerary: [
      { day: 1, activity: 'Arrival in Cairo, visit Khan el-Khalili bazaar' },
      { day: 2, activity: 'Full day tour of the Giza Plateau: Pyramids, Sphinx, and Solar Boat Museum' },
      { day: 3, activity: 'Visit the Egyptian Museum and departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1572252433829-d6a3c659d832?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxFeWdpdCUyMHRyYXZlbHxlbnwwfHx8MTc1Mjg4MTM3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Luxor: Valley of the Kings',
    destination: 'Luxor',
    type: 'Cultural',
    duration: 4,
    priceTiers: [
        { minPeople: 1, maxPeople: 1, pricePerAdult: 200, pricePerChild: 100 },
        { minPeople: 2, maxPeople: 5, pricePerAdult: 120, pricePerChild: 70 },
        { minPeople: 6, maxPeople: null, pricePerAdult: 100, pricePerChild: 60 },
    ],
    description: 'Discover the treasures of ancient Thebes. Visit the Valley of the Kings, Karnak Temple, and Luxor Temple.',
    itinerary: [
      { day: 1, activity: 'Arrival in Luxor, visit Luxor Temple at night' },
      { day: 2, activity: 'Explore the Valley of the Kings and Hatshepsut\'s Temple' },
      { day: 3, activity: 'Visit Karnak Temple Complex and Luxor Museum' },
      { day: 4, activity: 'Hot air balloon ride over the West Bank and departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1576487248805-cf4d8e504829?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxMdXhvciUyMFryb3NzfGVufDB8fHx8MTc1Mjg4MTM3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Nile Cruise from Aswan',
    destination: 'Aswan',
    type: 'Relaxation',
    duration: 5,
    priceTiers: [
        { minPeople: 1, maxPeople: 1, pricePerAdult: 300, pricePerChild: 150 },
        { minPeople: 2, maxPeople: 5, pricePerAdult: 250, pricePerChild: 125 },
        { minPeople: 6, maxPeople: null, pricePerAdult: 220, pricePerChild: 110 },
    ],
    description: 'Sail the majestic Nile River from Aswan to Luxor. Enjoy stunning scenery, visit ancient temples, and relax on a luxury cruise.',
    itinerary: [
      { day: 1, activity: 'Embark in Aswan, visit the High Dam and Philae Temple' },
      { day: 2, activity: 'Sail to Kom Ombo and visit the temple' },
      { day: 3, activity: 'Sail to Edfu, visit Horus Temple' },
      { day: 4, activity: 'Sail to Luxor, visit East Bank (Karnak & Luxor Temples)' },
      { day: 5, activity: 'Disembark and departure from Luxor' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1601639773191-23d537ddc1e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxBc3dhbiUyMEVneXB0fGVufDB8fHx8MTc1Mjg4MTM3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
  },
  {
    id: '4',
    name: 'Red Sea Diving Adventure',
    destination: 'Sharm El Sheikh',
    type: 'Adventure',
    duration: 7,
     priceTiers: [
        { minPeople: 1, maxPeople: 1, pricePerAdult: 350, pricePerChild: 180 },
        { minPeople: 2, maxPeople: 5, pricePerAdult: 280, pricePerChild: 150 },
        { minPeople: 6, maxPeople: null, pricePerAdult: 250, pricePerChild: 130 },
    ],
    description: 'Dive into the vibrant coral reefs of the Red Sea. A world-class diving experience for beginners and experts alike.',
    itinerary: [
        { day: 1, activity: 'Arrival in Sharm El Sheikh, check into resort' },
        { day: 2, activity: 'Dive briefing and first two dives in Ras Mohammed National Park' },
        { day: 3, activity: 'Thistlegorm wreck dive day trip' },
        { day: 4, activity: 'Relaxation or optional desert quad biking' },
        { day: 5, activity: 'Two dives at Tiran Island' },
        { day: 6, activity: 'Free day for beach and resort activities' },
        { day: 7, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1607595304128-2d5b6a7e6c0c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxTaGFybSUyMEVsJTIwU2hlaWtoJTIwRGl2aW5nfGVufDB8fHx8MTc1Mjg4MTM3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 5.0,
  },
  {
    id: '5',
    name: 'Hurghada Beach Getaway',
    destination: 'Hurghada',
    type: 'Relaxation',
    duration: 6,
    priceTiers: [
        { minPeople: 1, maxPeople: 1, pricePerAdult: 250, pricePerChild: 120 },
        { minPeople: 2, maxPeople: 5, pricePerAdult: 180, pricePerChild: 90 },
        { minPeople: 6, maxPeople: null, pricePerAdult: 160, pricePerChild: 80 },
    ],
    description: "Relax on the sunny beaches of Hurghada. Enjoy watersports, fresh seafood, and the vibrant resort atmosphere.",
    itinerary: [
      { day: 1, activity: 'Arrival in Hurghada' },
      { day: 2, activity: 'Full day at the beach and swimming' },
      { day: 3, activity: 'Snorkeling trip to Giftun Island' },
      { day: 4, activity: 'Explore Hurghada Marina and enjoy local cuisine' },
      { day: 5, activity: 'Free day for shopping or relaxing' },
      { day: 6, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1616262495333-33633842c65a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxIdXJnaGFkYSUyMEJlYWNofGVufDB8fHx8MTc1Mjg4MTM3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
  },
  {
    id: '6',
    name: 'Alexandria: Pearl of the Mediterranean',
    destination: 'Alexandria',
    type: 'Cultural',
    duration: 3,
    priceTiers: [
        { minPeople: 1, maxPeople: 1, pricePerAdult: 180, pricePerChild: 90 },
        { minPeople: 2, maxPeople: 5, pricePerAdult: 110, pricePerChild: 60 },
        { minPeople: 6, maxPeople: null, pricePerAdult: 95, pricePerChild: 50 },
    ],
    description: 'Explore the historic city of Alexandria. Visit the modern library, Roman amphitheater, and enjoy the Mediterranean sea breeze.',
    itinerary: [
        { day: 1, activity: 'Arrival in Alexandria, check-in and walk along the Corniche' },
        { day: 2, activity: 'Visit the Library of Alexandria, Catacombs of Kom El Shoqafa, and Pompey\'s Pillar' },
        { day: 3, activity: 'Explore Montaza Palace Gardens and departure' },
    ],
    availability: false,
    image: 'https://images.unsplash.com/photo-1623674620242-613d6a7e6c0c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxBcHJpbCUyMDIwMjQlMjBBbGV4YW5kcmlhJTIwRWd5cHR8ZW58MHx8fHwxNzUyODgxMzcyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.6,
  }
];

// @ts-ignore
export const getTours = (): Tour[] => tours.filter(tour => tour.priceTiers);

export const getTourById = (id: string): Tour | undefined => getTours().find(tour => tour.id === id);